.\"	$snafu: garload.1,v 1.6 2001/06/13 22:21:26 marc Exp $
.\"
.\"	Copyright (c) 1998, 2001 Marco S. Hyman
.\"
.\"	Permission to copy all or part of this material with or without
.\"	modification for any purpose is granted provided that the above
.\"	copyright notice and this paragraph are duplicated in all copies.
.\"
.\"	THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\"	IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\"	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.Dd May 7, 1998
.Dt GARLOAD 1
.Os SNAFU\ Software
.Sh NAME
.Nm garload
.Nd load waypoints, routes, and tracks to a Garmin GPS unit
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl d Ar debug-level
.Op Fl p Ar port
.Sh DESCRIPTION
.Nm
will load waypoint, route, and/or tracking information to a Garmin GPS unit
from standard input.  The data is expected to be in the format dumped
by
.Xr gardump 1 .
The input can be re-directed from a file, loading data that was
dumped using gardump and then massaged with your favorite text editor.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Display the software version on stderr and exit with a return code of 1.
.It Fl d Ar debug-level
Enable various levels of debugging output.  Without this option
debugging is disabled and only critical errors are written to
stderr.  Additional debug output at the various levels are:
.Bl -tag -width Ds
.It 1
Write all error messages to stderr.
.It 2
Write status messages to stderr.
.It 3
Write Garmin application protocol status to stderr.
.It 4
Perform a hex dump of all data going in and out of the Garmin
layer 2 protocol machine.  Data is written to stdout.
.It 5
Perform a hex dump of all data read from/written to the GPS
unit.
.El
.It Fl p Ar port
Use
.Ar port
as the device connected to the GPS unit.  The default port is a
compile time option.
.El
.Pp
.Nm
reads stdin and determines what to do based upon the data read.
Data is assumed to be in the format created by
.Xr gardump 1 .
That program outputs waypoints, routes, and track logs, preceding
each section by a ``comment'' in square brackets.
.Nm
uses the ``comment' to determine what data to upload.  The ``comments''
acted upon are:
.Bl -tag -width Ds
.It [waypoints, n records]
Begin upload of waypoints.  The number of records is ignored.
Waypoints use this format:
.Bd -literal -offset indent
xxxxxx -99.99999 -999.99999 sssss/d comments

.Ed
where the fields are waypoint name, latitude, longitude, symbol type,
symbol display option, and comments.  Comments can be up to 40 characters.
.It [routes, n records]
Begin upload of routes.  The number of records is ignored.  Routes are
composed of a route header followed by route waypoints.  A route header
looks like:
.Bd -literal -offset indent
**n comment

.Ed
where `n' is the route number.  Route waypoints are identical to normal
waypoints and are described above.
.It [tracks, n records]
Begin upload of a track log.  A track log entry looks like:
.Bd -literal -offset indent
-99.999999 -999.999999 yymmddhhmmss start

.Ed
The start field is optional.  Also, the time/date field is ignored
on upload.  It may read ``unknown'' if the dump was of a compressed
track log or of a previous uploaded track log.
.It [end transfer, n/m records]
Terminate any existing upload.
.El
.Pp
Each tranfer should be terminated by an `[end transfer...] record before
the next transfer is started.
.Nm
will ignore any line where the first non-blank character is ``#''. This
allows comments to be added to files that will be processed by
.Nm garload .
.\".SH ENVIRONMENT
.\".SH FILES
.\".SH EXAMPLES
.\".SH DIAGNOSTICS
.Sh SEE ALSO
.Xr gardump 1
.\".Sh HISTORY
.Sh AUTHORS
Marco S. Hyman using information from the published GARMIN GPS Interface
Specification, dated May 6, 1998 and the note OBSERVATIONS OF THE
GARMIN-GARMIN PROTOCOL by william.soley@sun.com and werme@zk3.dec.com.
.Sh BUGS
Tested with a Garmin GPS III and GPS III+ using OpenBSD versions
2.3 through 2.9 running on SPARC and i386.  May not work with other
GPS units or operating systems
