# $Id: Makefile,v 1.1 1998/05/12 05:01:15 marc Exp $
#
# Garmin communications protocol library
#
LIB=		garmin
NOPROFILE=	yes
NOPIC=		yes

SRCS=		gps1.c gps2.c gpsdisplay.c gpsprod.c gpscap.c gpsdump.c \
		gpsprint.c

install:

.include <bsd.lib.mk>
