# $snafu: Makefile,v 1.5 2001/05/02 00:34:53 marc Exp $
#
# Garmin communications protocol library
#
LIB=		garmin
NOPROFILE=	yes
NOPIC=		yes
NOLINT=		yes

SRCS=		gps1.c gps2.c gpsdisplay.c gpsprod.c gpscap.c gpsdump.c \
		gpsprint.c gpsversion.c gpsformat.c gpsload.c

install:

.include <bsd.lib.mk>
