# $snafu: Makefile,v 2.1 2004/08/19 02:45:29 marc Exp $
#
# Garmin communications protocol library
#
LIB=		garmin
NOPROFILE=	yes
NOPIC=		yes
NOLINT=		yes

SRCS=		gps1.c gps2.c gpsdisplay.c gpsprod.c gpscap.c gpsdump.c \
		gpsprint.c gpsversion.c gpsformat.c gpsload.c gpsfloat.c

install:

.include <bsd.lib.mk>
